In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic = time.time()
c=np.dot(a,b)
toc=time.time()

print(c)
print('Vectorized version:' + str(1000*(toc-tic))+"ms")


c = 0 
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
    
toc=time.time()
print(c)
print("For loop:"+str(1000*(toc-tic)) + "ms")

249718.69576733466
Vectorized version:1.5115737915039062ms
249718.69576733344
For loop:921.1668968200684ms


In [11]:
myarray = np.arange(0,10)

In [12]:
myarray


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
myexp = np.exp(myarray)

In [14]:
myexp

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])