In [1]:
import numpy as np


C:\Users\Wechuli\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")


In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic = time.time()
c=np.dot(a,b)
toc=time.time()

print(c)
print('Vectorized version:' + str(1000*(toc-tic))+"ms")


c = 0 
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
    
toc=time.time()
print(c)
print("For loop:"+str(1000*(toc-tic)) + "ms")

250224.81618447712
Vectorized version:1.0128021240234375ms
250224.81618448638
For loop:580.9974670410156ms


In [11]:
myarray = np.arange(0,10)

In [12]:
myarray


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
myexp = np.exp(myarray)

In [14]:
myexp

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])